drop table customer;
drop table dates;
drop table part;
drop table supplier;
drop table lineorder;
create table customer stored as orc as select * from ssb_${SCALE}_raw.customer ;
create table dates stored as orc as select * from ssb_${SCALE}_raw.dates;
create table part stored as orc as select * from ssb_${SCALE}_raw.part ;
create table supplier stored as orc as select * from ssb_${SCALE}_raw.supplier ;
create table lineorder stored as orc as select * from ssb_${SCALE}_raw.lineorder;
